### ISSUE TITLE
Vale not working in CLI Mode after VSCode upgrade

### ISSUE THREAD

**Issue by JeffreyNovotny** [errata-ai/vale-vscode#49] opened 2021-03-08 10:23 UTC
My VSCode application auto-upgraded to a new version, and now I find that my Vale extension doesn't work, at least for markdown files. I'm using Vale in CLI mode, and am not using Vale Server. It's not catching spelling errors, extra spaces, or anything really.

I am using a Mac environment. I upgraded Vale with homebrew (now using 2.9.1) and tried reinstalling Code, Vale itself, and disabling and re-enabling the extension. I also tried unchecking and re-checking Vale:Core:Use CLI.

Is this a known issue? Please let me know if you need more information from me.

The version of my Vale extension is 0.14.2. My version of VSCode is 1.54.1.

**Comment by jdkato** [comment] 2021-03-08 18:52
I'm using the same versions without any issues, as far as I can tell. Could you check the "Vale" output console (as shown below)?

![Screen Shot 2021-03-08 at 10 51 15 AM](https://user-images.githubusercontent.com/8785025/110367319-5e915100-7ffc-11eb-8f27-6e7ac39a7b88.png)

**Comment by JeffreyNovotny** [comment] 2021-03-08 19:10
I see the following errors:
E100 [.vale.ini] Runtime error

open : no such file or directory

Execution stopped with code 1.

But I do see the .vale.ini file. It's 6 levels up from my current directory. There's nothing in Vale/Vale CLI/Config, so it should be looking in the default places.

**Comment by ChrisChinchilla** [comment] 2021-03-09 07:48
I had hit some strange issues with recent versions of Vale and/or the extension, but I'll admit, I hadn't quite got around to digging further, if I figure out what it is, and if this issue is related, I'll let everyone know :)

**Comment by JeffreyNovotny** [comment] 2021-03-09 08:17
Thanks, Chris. Thinking back more closely, I now believe I had a general problem with the Vale extension after the Visual Code upgrade (as I checked several files in different locations) that I likely solved by uninstalling and reinstalling the extension. But I then ran into the specific problem I mentioned in my last posting that was unrelated to the original issue. I now realize that I didn't debug this carefully enough or track my steps properly, but hopefully this information is helpful.

**Comment by Haprog** [comment] 2021-03-17 09:19
I'm just currently trying to start using the Vale extension for the first time but can't get it to show anything even though I've set it to use CLI in the settings (I also tried with and without explicitly setting vale CLI path and config path in extension settings but that didn't help). Apparently it works ok for a colleague in the same project.

I'm on VS Code 1.54.3 on Linux, vale 2.10.1

Vale works fine for me if I run it manually from the terminal for a directory or a specific file.

I did notice that the Vale OUTPUT tab in VS Code often shows:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
```

**Comment by ChrisChinchilla** [comment] 2021-03-17 11:11
I am again experiencing issues myself. I am on Holiday next week, so will dedicate some time to the extension :)

**Comment by DIRECTcut** [comment] 2021-03-18 12:51
I'm having issues with VSCode 1.54.1 and the latest Vale CLI (v1.10.1, installed via Homebrew) on macOS v11.1.

What I did:

1. Installed vale with Homebrew:
`brew install vale`
2. Installed the extension from VSCode Extensions Marketplace
3. Enabled `Use Vale CLI` in the extension settings
4. Added a path to the binary:
`/opt/homebrew/bin/vale`

The result is no output from vale on the `Problems` panel in VSCode (`Output` was empty as well).

What I've tried:

1. I've launched the binary manually, and it works flawlessly in the shell.
2. I've downloaded [the latest binary](https://github.com/errata-ai/vale/releases) manually, copied it to my machine, and set a path in extension settings, to no avail. 
3. I've copied the manually downloaded binary into my workspace folder, updated the path in settings, but no dice.

What **has worked** for me:

I've downloaded [Vale v2.6.0](https://github.com/errata-ai/vale/releases/tag/v2.6.0) and replaced the binary on my machine with that. Now everything works: there is output in the `Problems` panel in VSCode.

Hope this helps.
Anyway, thanks for the great product!

**Comment by ChrisChinchilla** [comment] 2021-03-19 19:31
@jdkato I think I have tracked down the issue… There's a bunch of code that relies on getting paths from `vale ls-config`, and since something changed (I guess with a recent vale update), it looks like `vale ls-config` no longer returns anything, which causes a whole bunch of other things to break.

<img width="1386" alt="Screen Shot 2021-03-19 at 20 30 16" src="https://user-images.githubusercontent.com/42080/111833102-f55de780-88f1-11eb-92ab-643711a9e3da.png">

**Comment by jdkato** [comment] 2021-03-20 19:09
Thanks for looking into this. It should be fixed in v2.10.2.

**Comment by ChrisChinchilla** [comment] 2021-03-21 17:33
I can confirm that upgrading fixes these issues for me, if this isn't the same for anyone else on this thread, open a new issue and let us know :)

**Closed by ChrisChinchilla** 2021-03-21 17:33 UTC

**Comment by Haprog** [comment] 2021-03-24 08:34
I can confirm. After upgrading Vale to `2.10.2` with `brew upgrade vale` and running the "reload window" command in VS Code (or restarting it) the Vale extension seems to work now. Thanks!

**Comment by lvh** [comment] 2022-08-15 11:46
https://formulae.brew.sh/formula/vale currently has 2.20.1, which appears to have the same issue again. (Maybe I should open a different ticket?)

**Comment by v3ss0n** [comment] 2022-11-26 15:42
It dosen't work , versuon 2.20.2
