### ISSUE TITLE
v0.15.0 does not work with a fresh vale install

### ISSUE THREAD

**Issue by jessicajaniuk** [errata-ai/vale-vscode#93] opened 2022-08-03 18:50 UTC
I just followed all the fresh instructions for installing this extension. I'm on a mac running MacOS 12.5. Homebrew vale install is brand new. VSCode version is 1.69.2. After installing the vale vscode extension, I updated the settings with the proper paths. After restarting MacOS and restarting VSCode, any time I visit a file that needs linting, I get this output in the vscode output tab:

```
[2022-08-03 11:41:49.054] [renderer1] [error] Cannot read properties of null (reading '0'): TypeError: Cannot read properties of null (reading '0')
	at d.<anonymous> (/Users/jessicajaniuk/.vscode/extensions/errata-ai.vale-server-0.15.0/dist/extension.js:1:4562)
	at Generator.next (<anonymous>)
	at /Users/jessicajaniuk/.vscode/extensions/errata-ai.vale-server-0.15.0/dist/extension.js:1:2770
	at new Promise (<anonymous>)
	at s (/Users/jessicajaniuk/.vscode/extensions/errata-ai.vale-server-0.15.0/dist/extension.js:1:2515)
	at d.provideCodeActions (/Users/jessicajaniuk/.vscode/extensions/errata-ai.vale-server-0.15.0/dist/extension.js:1:4430)
	at k.provideCodeActions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:87:42489)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:87:72554
	at te._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:87:66659)
	at te.$provideCodeActions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:87:72530)
	at s._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:95:13708)
	at s._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:95:13390)
	at s._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:95:12107)
	at s._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:95:10853)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:95:8957
	at w.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at v.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at a.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:18976)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:34679
	at w.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at v.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at a.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:18976)
	at r._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:23563)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:21097
	at w.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at v.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at p.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:15807)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:14937
	at Socket.R (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:13763)
	at Socket.emit (node:events:390:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
```

Reverting to the prior version of the extension 0.14.2 with the same settings for path, clicking the use CLI checkbox, everything works. I've been able to run vale in the command line with no problems the whole time post initial install. Let me know if you'd like additional info. I'd be happy to provide it.

**Comment by jessicajaniuk** [comment] 2022-08-03 18:52
Additional info: Homebrew reports I'm running vale 2.20.1.

**Comment by apupier** [comment] 2022-08-05 11:59
I think it is a duplicate of https://github.com/errata-ai/vale-vscode/issues/90

**Comment by jessicajaniuk** [comment] 2022-08-10 17:57
This issue is unfortunately still present on 0.15.1. I upgraded today and still see these same messages.

**Comment by ChrisChinchilla** [comment] 2022-08-11 12:57
@jessicajaniuk In this case you might be falling for the problem that I feared might happen. And that you now have settings that match the __new__ settings paths, when you actually need to revert them to the __old__ ones. Try that first and let me know.

**Comment by jessicajaniuk** [comment] 2022-08-11 16:07
@ChrisChinchilla I'm not following what you mean. I've been switching back and forth between 0.14.2 and 0.15.1 this morning trying to figure out the difference and I'm not seeing it. Maybe you can clarify what needs to change here, since 0.14.2 works with these settings.

Here's the settings UI for 0.14.2
![Screen Shot 2022-08-11 at 8 44 10 AM](https://user-images.githubusercontent.com/72768744/184178358-e5fd5ee3-6558-46b0-a26e-12532bfbfc03.png)

Here's the settings UI for 0.15.1
![Screen Shot 2022-08-11 at 9 02 32 AM](https://user-images.githubusercontent.com/72768744/184178431-b401f144-c236-4665-999c-081e452e13f8.png)

The JSON looks like this in both cases:
```
{
    "vale.config": "~/repos/angular/aio/tools/doc-linter/vale.ini",
    "vale.path": "/usr/local/bin/vale",
    "vale.core.useCLI": true,
    "vale.valeCLI.config": "Users/jessicajaniuk/repos/angular/aio/tools/doc-linter",
    "vale.valeCLI.path": "/usr/local/bin/vale"
}
```

The difference I see is that with 0.14.2, the `vale.core.useCLI` shows as being used, while not being used in 0.15.1. The `vale.config` and `vale.path` show as inactive in both. Let me know what I've missed.

**Comment by jdkato** [comment] 2022-08-11 20:19
This issue and #98 actually aren't related to the extension's configuration. They are both related to the action code changes introduced in v0.15.0.

I can reproduce the error messages, but the extension never stops working for me. I assume that isn't the case here, though?

**Comment by jessicajaniuk** [comment] 2022-08-11 20:30
That's tough to suss out at this point. With the clean install, I _think_ it wasn't working, but it's been about a week since then. I'm pretty sure it was not working at all until I reverted to 0.14.2. That's when I started seeing squigglies and what not. Now when I shift back and forth, it seems that the extension is working in both cases, but I see these error messages in the output, which is very noisy. So I think it's still possibly broken for a fresh install.

**Comment by jdkato** [comment] 2022-08-11 21:11
Could you verify that everything is working as expected in the newly-released v0.15.2?

The error messages should be gone and your config settings should be loaded correctly.

**Comment by jessicajaniuk** [comment] 2022-08-11 21:20
@jdkato Just verified that it's working with 0.15.2 with no error messages in the output. 🙌🏻

**Comment by jessicajaniuk** [comment] 2022-08-11 21:24
@jdkato The Angular team is using Vale on our documentation, and this extension will be super helpful for us. We appreciate your work. Thanks for working through this with me.

**Closed** 2022-08-11 21:44 UTC
Labels: bug
